import pandas as pd

def get_earliest_and_latest(messages, sender=None):
    # Generated by ChatGPT
    if sender is not None:
        filtered = [m for m in messages if m.get("phone_number") == sender]
    else:
        filtered = messages

    if not filtered:
        raise ValueError("No messages found for the given sender filter")

    earliest = min(filtered, key=lambda m: m["date_obj"])
    latest   = max(filtered, key=lambda m: m["date_obj"])
    return earliest, latest

def stat_overview(messages):
    """Generates an overview of general statistics from iMessage data."""
    print("Calculating statistical overview...")

    earliest, latest = get_earliest_and_latest(messages)
    earliest_msg = earliest["date"]
    latest_msg = latest["date"]

    total = len(messages)

    mesg_sent = sum(1 for m in messages if m.get("is_from_me"))
    mesg_received = total - mesg_sent
    percent_sent = (mesg_sent / total) * 100 if total > 0 else 0
    percent_received = 100 - percent_sent

    senders = set()
    for m in messages:
        if m.get("is_from_me") == 0:
            if m.get("phone_number") not in senders:
                senders.add(m.get("phone_number"))
            else: continue
    
    recipients = set()
    for m in messages:
        if m.get("is_from_me") == 1:
            if m.get("phone_number") not in recipients:
                recipients.add(m.get("phone_number"))
            else: continue

    group_chats = set()
    for m in messages:
        if m.get("cache_roomname"):
            if m.get("cache_roomname") not in group_chats:
                group_chats.add(m.get("cache_roomname"))
            else: continue

    non_gc_convos = set()
    for m in messages:
        if not m.get("cache_roomname"):
            if m.get("phone_number") not in non_gc_convos:
                non_gc_convos.add(m.get("phone_number"))
            else: continue
    
    unique_convos = len(group_chats) + len(non_gc_convos)
    percent_gc = (len(group_chats) / unique_convos) * 100 if unique_convos > 0 else 0

    print("\niMessage Statistical Overview")
    print("=" * 40)
    print(f"\nTime period: {earliest_msg} to {latest_msg}")
    print(f"\nTotal messages: {total}")
    print(f"\nMessages sent: {mesg_sent} ({percent_sent:.2f}%)")
    print(f" - Unique message recipients: {len(recipients)}")
    print(f"\nMessages received: {mesg_received} ({percent_received:.2f}%)")
    print(f" - Unique message senders: {len(senders)}")
    print(f"\nUnique conversations: {unique_convos}")
    print(f" - Group chats: {len(group_chats)} ({percent_gc:.2f}%)")

    return [earliest_msg, 
            latest_msg, 
            total, 
            mesg_sent, 
            percent_sent, 
            recipients,
            mesg_received, 
            percent_received, 
            senders,
            unique_convos,
            group_chats,
            percent_gc
    ]   

def get_avg_message_length(messages):
    total_message_length = 0
    message_count = 0
    for m in messages:
        if m.get("is_from_me") == 1:
            message = m["body"].split(" ")
            total_message_length += len(message)
            message_count += 1
    average_message_length = total_message_length/message_count

    return average_message_length

def get_msg_times(messages, is_from_me):

    df = pd.DataFrame(messages)
    focus_messages = df[df["is_from_me"] == int(is_from_me)].copy()

    if focus_messages.empty:
        return "N/A", 0, 0.0

    hours = focus_messages["date_obj"].dt.hour

    periods = [0, 5, 9, 12, 17, 20, 24]
    labels = ["Early Morning", "Morning", "Prenoon", "Afternoon", "Evening", "Night"]

    focus_messages["period"] = pd.cut(hours, bins = periods, labels = labels, right = False, ordered = False)

    period_counts = focus_messages["period"].value_counts()

    top_period = period_counts.idxmax()
    top_count = period_counts.max()

    total_messaeges = len(focus_messages)
    percent_top = (top_count / total_messaeges) * 100

    return top_period, percent_top

def get_attachment_percentage(messages):

    df = pd.DataFrame(messages)
    attachments = df[df["cache_has_attachments"] == 1].copy()

    percent_attachments = len(attachments)/len(df)

    return percent_attachments

def get_avg_user_response_time(messages):

    df = pd.DataFrame(messages)
    df_1 = df[df["cache_roomname"].isna()].copy()

    df_1['date'] = pd.to_datetime(df_1['date'])

    results = []
    for phone_number, group in df_1.groupby("phone_number"):
        group = group.sort_values("date")

        prev_sender = group['is_from_me'].shift(1)
        prev_date = group['date'].shift(1)
        is_reply = (group['is_from_me'] == 1) & (prev_sender == 0)

        reply_times = group.loc[is_reply, 'date'] - prev_date.loc[is_reply]

        if not reply_times.empty:
            avg_time = reply_times.mean()
            results.append({
                'phone_number': phone_number, 
                'avg_reply_time': avg_time,
                'reply_count': len(reply_times) 
            })

    results_df = pd.DataFrame(results)
    average_response_time = results_df["avg_reply_time"].mean()

    return average_response_time

def habit_overivew(messages):
    """Generates an overview of user messaging habits"""
    
    print("Calculating habit statistics...")

    avg_mesg_length = get_avg_message_length(messages)

    sent_msg_period, sent_period_percent = get_msg_times(messages, 1)

    rec_msg_period, rec_period_percent = get_msg_times(messages, 0)

    percent_attachments = get_attachment_percentage(messages)

    average_response_time = get_avg_user_response_time(messages)

    return [
        avg_mesg_length,
        sent_msg_period,
        sent_period_percent,
        rec_msg_period,
        rec_period_percent,
        percent_attachments,
        average_response_time
    ]


    





