import pandas as pd

def get_earliest_and_latest(messages, sender=None):
    # Generated by ChatGPT
    messages = pd.DataFrame(messages)
    if sender is not None:
        mask = messages["convo_id"].str.lower().str.strip() == sender.lower().strip()
        filtered = messages[mask]
    else:
        filtered = messages

    if not filtered:
        raise ValueError(f"No messages found for sender: {sender}")

    earliest = filtered["date_obj"].min()
    latest   = filtered["date_obj"].max()
    return earliest, latest

def stat_overview(messages):
    """Generates an overview of general statistics from iMessage data."""
    print("Calculating statistical overview...")

    earliest, latest = get_earliest_and_latest(messages)
    earliest_msg = earliest["date"]
    latest_msg = latest["date"]

    total = len(messages)

    mesg_sent = sum(1 for m in messages if m.get("is_from_me"))
    mesg_received = total - mesg_sent
    percent_sent = (mesg_sent / total) * 100 if total > 0 else 0
    percent_received = 100 - percent_sent

    senders = set()
    for m in messages:
        if m.get("is_from_me") == 0:
            if m.get("phone_number") not in senders:
                senders.add(m.get("phone_number"))
            else: continue
    
    recipients = set()
    for m in messages:
        if m.get("is_from_me") == 1:
            if m.get("phone_number") not in recipients:
                recipients.add(m.get("phone_number"))
            else: continue

    group_chats = set()
    for m in messages:
        if m.get("cache_roomname"):
            if m.get("cache_roomname") not in group_chats:
                group_chats.add(m.get("cache_roomname"))
            else: continue

    non_gc_convos = set()
    for m in messages:
        if not m.get("cache_roomname"):
            if m.get("phone_number") not in non_gc_convos:
                non_gc_convos.add(m.get("phone_number"))
            else: continue
    
    unique_convos = len(group_chats) + len(non_gc_convos)
    percent_gc = (len(group_chats) / unique_convos) * 100 if unique_convos > 0 else 0

    return [earliest_msg, 
            latest_msg, 
            total, 
            mesg_sent, 
            percent_sent, 
            recipients,
            mesg_received, 
            percent_received, 
            senders,
            unique_convos,
            group_chats,
            percent_gc
    ]   

def get_avg_message_length(messages, convo=None):
    df = pd.DataFrame(messages)
    if convo is not None:
        mask = df["convo_id"].str.strip().str.lower() == convo.strip().lower()
        filtered = df[mask]
    else:
        filtered = df

    sent_messages = df[df["is_from_me"] == 1].copy()
    if sent_messages.empty:
        return 0.0
    
    word_counts = sent_messages["body"].astype(str).str.split().str.len()
    average_length = round(word_counts.mean(), 2)
    

    return average_length

def get_msg_times(messages, is_from_me):

    df = pd.DataFrame(messages)
    focus_messages = df[df["is_from_me"] == int(is_from_me)].copy()

    if focus_messages.empty:
        return "N/A", 0, 0.0

    hours = focus_messages["date_obj"].dt.hour

    periods = [0, 5, 9, 12, 17, 20, 24]
    labels = ["Early Morning (12 AM - 4:59 AM)", "Morning (5 AM - 8:59 AM)", "Prenoon (9 AM - 11:59 AM)", "Afternoon (12 PM - 4:59 PM)", "Evening (5 PM - 7:59 PM)", "Night (8 PM - 11:59 PM)"]

    focus_messages["period"] = pd.cut(hours, bins = periods, labels = labels, right = False, ordered = False)

    period_counts = focus_messages["period"].value_counts()

    top_period = period_counts.idxmax()
    top_count = period_counts.max()

    total_messaeges = len(focus_messages)
    percent_top = round((top_count / total_messaeges) * 100, 2)

    return top_period, percent_top

def get_attachment_percentage(messages):

    df = pd.DataFrame(messages)
    attachments = df[df["cache_has_attachments"] == 1].copy()

    percent_attachments = round(len(attachments)/len(df), 2)

    return percent_attachments

def get_avg_user_response_time(messages):

    df = pd.DataFrame(messages)
    df_1 = df[df["cache_roomname"].isna()].copy()

    df_1['date'] = pd.to_datetime(df_1['date'])

    results = []
    for phone_number, group in df_1.groupby("phone_number"):
        group = group.sort_values("date")

        prev_sender = group['is_from_me'].shift(1)
        prev_date = group['date'].shift(1)
        is_reply = (group['is_from_me'] == 1) & (prev_sender == 0)

        reply_times = group.loc[is_reply, 'date'] - prev_date.loc[is_reply]

        if not reply_times.empty:
            avg_time = reply_times.mean()
            results.append({
                'phone_number': phone_number, 
                'avg_reply_time': avg_time,
                'reply_count': len(reply_times) 
            })

    results_df = pd.DataFrame(results)
    average_response_time = results_df["avg_reply_time"].mean()

    components = average_response_time.components

    days = components.days
    hours = components.hours
    minutes = components.minutes
    seconds = components.seconds

    response_time = []
    if days > 0:
        response_time.append(f"{days} days")
    if hours > 0:
        response_time.append(f"{hours} hours")
    if minutes > 0:
        response_time.append(f"{minutes} minutes")
    if seconds > 0:
        response_time.append(f"{seconds} seconds")
    if not days and not hours and not minutes and not seconds:
        response_time.append("ERROR")

    response_time_str = ", ".join(response_time)

    return response_time_str

def habit_overivew(messages):
    """Generates an overview of user messaging habits"""
    
    print("Calculating habit statistics...")

    avg_mesg_length = get_avg_message_length(messages)

    sent_msg_period, sent_period_percent = get_msg_times(messages, 1)

    rec_msg_period, rec_period_percent = get_msg_times(messages, 0)

    percent_attachments = get_attachment_percentage(messages)

    average_response_time = get_avg_user_response_time(messages)

    return [
        avg_mesg_length,
        sent_msg_period,
        sent_period_percent,
        rec_msg_period,
        rec_period_percent,
        percent_attachments,
        average_response_time
    ]

def social_network(messages):
    top_contacts = []
    df = pd.DataFrame(messages)
    top_convos = df["convo_id"].value_counts().head(10)


    for name, total_count in top_convos.items():
        convo_mask = df["convo_id"] == name
        convo_df = df[convo_mask]
        
        is_group_chat = "(Group Chat)" if convo_df["cache_roomname"].notna().any() else None
        
        earliest_msg = convo_df["date_obj"].min()
        latest_msg = convo_df["date_obj"].max()

        mesg_sent = convo_df["is_from_me"].sum()
        mesg_received = total_count - mesg_sent
        
        percent_sent = (mesg_sent / total_count) * 100 if total_count > 0 else 0
        percent_received = 100 - percent_sent

        habits = habit_overivew(convo_df)
        
        new_row = {
            "name": ,
            "total_count": total_count, 
            "is_group_chat": is_group_chat, 
            "earliest_msg": earliest_msg, 
            "latest_msg": latest_msg, 
            "mesg_sent": mesg_sent, 
            "mesg_received": mesg_received, 
            "percent_sent": percent_sent, 
            "percent_received": percent_received,
            "avg_mesg_length": habits[0],
            "sent_msg_period": habits[1],
            "sent_period_percent": habits[2],
            "rec_msg_period": habits[3],
            "rec_period_percent": habits[4],
            "percent_attachments": habits[5],
            "average_response_time": habits[6]
        }

        top_contacts.append(new_row)
        











        



        












    





