def get_earliest_and_latest(messages, sender=None):
    # Generated by ChatGPT
    if sender is not None:
        filtered = [m for m in messages if m.get("phone_number") == sender]
    else:
        filtered = messages

    if not filtered:
        raise ValueError("No messages found for the given sender filter")

    earliest = min(filtered, key=lambda m: m["date_obj"])
    latest   = max(filtered, key=lambda m: m["date_obj"])
    return earliest, latest

def stat_overview(messages):
    """Generates an overview of general statistics from iMessage data."""

    earliest, latest = get_earliest_and_latest(messages)
    earliest_msg = earliest["date"]
    latest_msg = latest["date"]

    total = len(messages)

    mesg_sent = sum(1 for m in messages if m.get("is_from_me"))
    mesg_received = total - mesg_sent
    percent_sent = (mesg_sent / total) * 100 if total > 0 else 0
    percent_received = 100 - percent_sent

    senders = set()
    for m in messages:
        if m.get("is_from_me") == 0:
            if m.get("phone_number") not in senders:
                senders.add(m.get("phone_number"))
            else: continue
    
    recipients = set()
    for m in messages:
        if m.get("is_from_me") == 1:
            if m.get("phone_number") not in recipients:
                recipients.add(m.get("phone_number"))
            else: continue

    group_chats = set()
    for m in messages:
        if m.get("cache_roomname"):
            if m.get("cache_roomname") not in group_chats:
                group_chats.add(m.get("cache_roomname"))
            else: continue

    non_gc_convos = set()
    for m in messages:
        if not m.get("cache_roomname"):
            if m.get("phone_number") not in non_gc_convos:
                non_gc_convos.add(m.get("phone_number"))
            else: continue
    
    unique_convos = len(group_chats) + len(non_gc_convos)
    



